# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [2.1.2]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2

      - name: Verify formatting
        working-directory: ./2024
        run: deno -v && deno fmt --check

      - name: Run linter
        working-directory: ./2024
        run: deno lint

      - name: Run tests
        working-directory: ./2024
        run: deno test -A
